services:
  - type: web
    name: naruto-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd nodejs-backend && npm install
    startCommand: cd nodejs-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: MONGODB_URI
        fromDatabase:
          name: game-data
          property: connectionString
